name: Cake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # this now uses a dedicated large runner from GitHub running the following specs:
    # 8-core, 32GB RAM, 300GB SSD
    # https://github.com/organizations/sourcegraph/settings/actions/runner-groups/6
    runs-on:
      # this group only allows access to this workflow
      group: cody-vs-large-runner
    # do we want to run this on forks?
    if: github.repository_owner == 'sourcegraph'

    steps:
    - uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3

    - name: ⚙️ Prepare Visual Studio
      run: '&"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSettings General.vssettings'

    - name: Install Cake.Tool
      run: dotnet tool install --global Cake.Tool

    - name: Restore NuGet packages
      run: nuget restore src\Cody.Core\Cody.Core.csproj -PackagesDirectory src\packages

    - name: Build Release
      run: |
        cd src
        dotnet tool restore
        corepack enable
        corepack install --global pnpm@8.6.7
        dotnet cake

    - name: Tests
      env: 
        Access_Token_UI_Tests: ${{ secrets.SRC_ACCESS_TOKEN_DOTCOM }}
      run: |
        cd src
        dotnet cake --target Tests
        dotnet test .\Cody.VisualStudio.Tests\bin\Debug\Cody.VisualStudio.Tests.dll -v detailed
